let g:number_of_src_files = 28
let g:parse_src_files_list = ['/g/g15/dubois9/src/vpi/src/kinds.f90', '/g/g15/dubois9/src/vpi/src/nl2sol.f90', '/g/g15/dubois9/src/vpi/src/rot_test.f90', '/g/g15/dubois9/src/vpi/src/timers.f90', '/g/g15/dubois9/src/vpi/src/vpi_aziz.f90', '/g/g15/dubois9/src/vpi/src/vpi_bbridge.f90', '/g/g15/dubois9/src/vpi/src/vpi_bisect.f90', '/g/g15/dubois9/src/vpi/src/vpi_blip.f90', '/g/g15/dubois9/src/vpi/src/vpi_coordinate_utils.f90', '/g/g15/dubois9/src/vpi/src/vpi_defines.f90', '/g/g15/dubois9/src/vpi/src/vpi_det.f90', '/g/g15/dubois9/src/vpi/src/vpi_gfn.f90', '/g/g15/dubois9/src/vpi/src/vpi_lattice.f90', '/g/g15/dubois9/src/vpi/src/vpi_main.f90', '/g/g15/dubois9/src/vpi/src/vpi_main.new.f90', '/g/g15/dubois9/src/vpi/src/vpi_main_test.f90', '/g/g15/dubois9/src/vpi/src/vpi_obdm.f90', '/g/g15/dubois9/src/vpi/src/vpi_opt.f90', '/g/g15/dubois9/src/vpi/src/vpi_phase_maps.f90', '/g/g15/dubois9/src/vpi/src/vpi_potential.f90', '/g/g15/dubois9/src/vpi/src/vpi_rand_utils.f90', '/g/g15/dubois9/src/vpi/src/vpi_read_input.f90', '/g/g15/dubois9/src/vpi/src/vpi_read_params.f90', '/g/g15/dubois9/src/vpi/src/vpi_rotation.f90', '/g/g15/dubois9/src/vpi/src/vpi_sample.f90', '/g/g15/dubois9/src/vpi/src/vpi_spline.f90', '/g/g15/dubois9/src/vpi/src/vpi_trial_func.f90', '/g/g15/dubois9/src/vpi/src/vpi_xij.f90']
syn keyword FortranFunction vpi_eval_dphase "subroutine 1363 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_radial_density "subroutine 1382 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_density_sp "subroutine 1402 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_optical_density "subroutine 1419 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_full_density "subroutine 1446 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_optical_density2 "subroutine 1470 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_n_r "subroutine 1497 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_n_z2 "subroutine 1516 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_corr_x "subroutine 1547 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_corr_phase "subroutine 1563 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_corr_r "subroutine 1577 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_corr_xz "subroutine 1596 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_gofr "subroutine 1613 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_eval_gof_rot "subroutine 1635 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
syn keyword FortranFunction vpi_accept_path "function 1680 /g/g15/dubois9/src/vpi/src/vpi_main.new.f90
let b:global_complete_dict = {'interface:vpi_eval_gof_rot': {'arg:order': []}, 'interface:vpi_eval_density_sp': {'arg:order': ['size_x', 'dndx'], 'size_x': [], 'dndx': []}, 'vpi_accept_path': ['logical', 'global', 'function', 'vpi_main.new.f90'], 'vpi_eval_n_z2': ['global', 'subroutine', 'vpi_main.new.f90'], 'vpi_eval_corr_phase': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_full_density': {'arg:order': []}, 'interface:vpi_eval_radial_density': {'arg:order': []}, 'interface:vpi_accept_path': {'arg:order': []}, 'vpi_eval_optical_density': ['global', 'subroutine', 'vpi_main.new.f90'], 'vpi_eval_optical_density2': ['global', 'subroutine', 'vpi_main.new.f90'], 'vpi_eval_gof_rot': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_gofr': {'arg:order': []}, 'vpi_eval_corr_xz': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_corr_xz': {'arg:order': []}, 'interface:vpi_eval_corr_r': {'arg:order': []}, 'interface:vpi_eval_corr_phase': {'move_start': [], 'phase': [], 'arg:order': ['corr_phase', 'phase', 'move_start', 'move_end'], 'corr_phase': [], 'move_end': []}, 'interface:vpi_eval_n_r': {'arg:order': []}, 'vpi_eval_corr_r': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_corr_x': {'arg:order': ['x'], 'x': []}, 'vpi_eval_gofr': ['global', 'subroutine', 'vpi_main.new.f90'], 'vpi_eval_corr_x': ['global', 'subroutine', 'vpi_main.new.f90'], 'vpi_eval_full_density': ['global', 'subroutine', 'vpi_main.new.f90'], 'vpi_eval_n_r': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_dphase': {'arg:order': []}, 'vpi_eval_density_sp': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_optical_density2': {'arg:order': []}, 'vpi_eval_dphase': ['global', 'subroutine', 'vpi_main.new.f90'], 'interface:vpi_eval_optical_density': {'arg:order': []}, 'interface:vpi_eval_n_z2': {'arg:order': []}, 'vpi_eval_radial_density': ['global', 'subroutine', 'vpi_main.new.f90']}